name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.0.5
        with:
          arch: aarch64
          distro: ubuntu18.04

          env: |
            DOCKERHUB_TOKEN: ${{ DOCKERHUB_TOKEN }}
            GHCR_TOKEN: ${{ GHCR_TOKEN }}

          install: |
            apt-get update -q -y
            apt-get install -q -y python3 git docker.io docker-compose
          run: |
            ./build.sh
            docker images
